tmux, airline, fonts

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -3,40 +3,51 @@
 repo_path=$HOME/.ha100
 
 check_variable() {
-    if test ! $(which vim); then
-        echo "Error: vim not found! Please install it first."
-        exit 1
-    fi
+  if test ! $(which vim); then
+    echo "Error: vim not found! Please install it first."
+    exit 1
+  fi
 
-    if [ -e $repo_path ]; then
-        echo "Error: $repo_path has already exist! Please remove it before install."
-        exit 1
-    fi
+  if [ -e $repo_path ]; then
+    echo "Error: $repo_path has already exist! Please remove it before install."
+    exit 1
+  fi
 }
 
 download_repo() {
-    git clone https://github.com/ha100/dotfiles.git $repo_path
-    if [ ! "$?" -eq '0' ]; then
-        echo "Error: clone repository failed!"
-        exit 1
-    fi
+  git clone https://github.com/ha100/dotfiles.git $repo_path
+  if [ ! "$?" -eq '0' ]; then
+    echo "Error: clone repository failed!"
+    exit 1
+  fi
 
-    pushd $repo_path
-    git submodule init && git submodule update --recursive
-    if [ ! "$?" -eq '0' ]; then
-        echo "Error: clone submodule failed!"
-        exit 1
-    fi
-    popd
+  pushd $repo_path
+  git submodule init && git submodule update --recursive
+  if [ ! "$?" -eq '0' ]; then
+    echo "Error: clone submodule failed!"
+    exit 1
+  fi
+  popd
+}
+
+download_fonts() {
+  git clone https://github.com/powerline/fonts.git
+  cd fonts
+  ./install.sh
+
+  cd ..
+  rm -rf fonts
 }
 
 link_files() {
-    ln -sf $HOME/.ha100/vimrc.symlink $HOME/.vimrc
-    ln -sf $HOME/.ha100/vim.symlink $HOME/.vim
+  ln -sf $HOME/.ha100/vimrc.symlink $HOME/.vimrc
+  ln -sf $HOME/.ha100/vim.symlink $HOME/.vim
+  ln -sf $HOME/.ha100/tmux.symlink $HOME/.tmux
 }
 
 check_variable
 download_repo
+download_fonts
 link_files
 $repo_path/install.sh
 
